version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: chatapp_db
    ports:
      - "27017:27017"
    volumes:
      - "/mongodb/data:/data/db"
    networks:
      - node-network
    restart: always
networks:
  node-network:
    driver: bridge